export const associatedJournals = [
{
  slug: "journal-of-animal-environment",
  title: "Journal of Animal Environment",
  issn: "2717-1388",
  category: "biology",
  indexingOptions: ["Scopus"],
  publisher: "Tehran: Amayesh Shale Consulting Engineers Company",
  ActiveYears: "2026",
  language: "English",
  image: "/images/JAE.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101445137",
  Aim:""
},

{
  slug: "natural-resources-for-human-health",
  title: "Natural Resources for Human Health (NRHHBF)",
  issn: "2583-1194",
  category: "environment-science-technology",
  indexing: ["Scopus"],
  publisher: "Visagaa Publishing House",
  ActiveYears: "2026",
  language: "English",
  image: "/images/NRHHBF.png",
  Scopus: "https://www.scopus.com/sourceid/21101166819",
},

{
  slug: "international-journal-of-artificial-intelligence-and-machine-learning",
  title:
    "International Journal of Artificial Intelligence and Machine Learning (IJAIML)",
  issn: "2789-2557",
  category: "computer-science",
  indexing: ["Scopus"],
  publisher: "SvedbergOpen",
  ActiveYears: "2026",
  language: "English",
  image: "/images/IJAIML.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101344619#tabs=2",
},

{
  slug: "genetics-and-molecular-research",
  title: "Genetics and Molecular Research",
  issn: "1676-5680",
  category: "biology",
  indexing: ["Scopus"],
  publisher: "Fundacao de Pesquisas Cientificas de Ribeirao Preto",
  ActiveYears: "2026",
  language: "English",
  image: "/images/GMR.png",
  Scopus: "https://www.scopus.com/sourceid/22190",
},

{
  slug: "international-journal-of-special-education",
  title: "International Journal of Special Education",
  issn: "0827-3383",
  category: "education",
  indexing: ["Scopus"],
  publisher: "SPED Ltd",
  ActiveYears: "2026",
  language: "English",
  image: "/images/IJSE.png",
  Scopus: "https://www.scopus.com/sourceid/33328",
},

{
  slug: "international-journal-of-drug-delivery-technologies",
  title: "International Journal of Drug Delivery Technologies",
  issn: "0975-4415",
  category: "pharmaceutical",
  indexing: ["Scopus"],
  publisher: "Dr. Yashwant Research Labs Pvt. Ltd.",
  ActiveYears: "2026",
  language: "English",
  image: "/images/IJDDT.jpeg",
  Scopus: "https://www.scopus.com/sourceid/20500195212",
},

{
  slug: "indian-journal-of-pharmaceutical-and-biological-research",
  title: "Indian Journal of Pharmaceutical and Biological Research",
  issn: "2320-9267",
  category: "pharmaceutical",
  indexing: ["Embase"],
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/IJPBR.png",
},

{
  slug: "enterprise-development-and-microfinance",
  title: "Enterprise Development and Microfinance",
  issn: "1755-1978",
  category: "business-management",
  indexing: ["Scopus"],
  publisher: "Practical Action Publishing",
  ActiveYears: "Discontinued 2026",
  language: "English",
  image: "/images/EDM.png",
  Scopus: "https://www.scopus.com/sourceid/19700186953",
},

{
  slug: "waterlines",
  title: "Waterlines",
  issn: "0262-8104",
  category: "environment-science-technology",
  indexing: ["Scopus"],
  publisher: "Practical Action Publishing",
  ActiveYears: "Discontinued 2026",
  language: "English",
  image: "/images/Waterline.jpeg",
  Scopus: "https://www.scopus.com/sourceid/19406",
},

{
  slug: "journal-of-daoist-studies",
  title: "Journal of Daoist Studies",
  issn: "1941-5516",
  category: "arts-humanities",
  indexing: ["Scopus"],
  publisher: "University of Hawaii Press",
  ActiveYears: "Discontinued 2026",
  language: "English",
  image: "/images/JDS.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101033328",
},

{
  slug: "international-journal-of-aquatic-research-and-environmental-studies",
  title:
    "International Journal of Aquatic Research and Environmental Studies",
  issn: "2980-7840",
  category: "environment-science-technology",
  indexing: ["Scopus"],
  publisher: "Green Wave Publication",
  ActiveYears: "Discontinued 2026",
  language: "English",
  image: "/images/IJARES.png",
  Scopus: "https://www.scopus.com/sourceid/21101262912",
},

{
  slug: "international-journal-of-computer-information-systems-and-industrial-management-applications",
  title:
    "International Journal of Computer Information Systems and Industrial Management Applications",
  issn: "2150-7988",
  category: "computer-science",
  indexing: ["Scopus"],
  publisher: "Cerebration Science Publishing",
  ActiveYears: "Discontinued 2026",
  language: "English",
  image: "/images/IJCISIM.png",
  Scopus: "https://www.scopus.com/sourceid/21100440516",
},

{
  slug: "frontiers-in-health-informatics",
  title: "Frontiers in Health Informatics",
  issn: "2676-7104",
  category: "health-informatics",
  indexing: ["Scopus"],
  publisher: "Iranian Medical Informatics Association (IrMIA)",
  ActiveYears: "Discontinued 2024",
  language: "English",
  image: "/images/FHI.png",
  Scopus: "https://www.scopus.com/sourceid/21101150092",
},

{
  slug: "international-journal-of-applied-engineering-and-technology",
  title: "International Journal of Applied Engineering and Technology (London)",
  issn: "2633-4828",
  category: "engineering",
  indexing: ["Scopus"],
  publisher: "Roman Science Publications and Distributions",
  ActiveYears: "Discontinued 2023",
  language: "English",
  image: "/images/IJAET.png",
  Scopus: "https://www.scopus.com/sourceid/21101052926",
},

{
  slug: "stochastic-modelling-and-computational-sciences",
  title: "Stochastic Modelling & Computational Sciences",
  issn: "2752-3829",
  category: "computer-science",
  indexing: ["Scopus"],
  publisher: "Roman Science Publications and Distributions",
  ActiveYears: "Discontinued 2023",
  language: "English",
  image: "/images/SMCS.png",
  Scopus: "https://www.scopus.com/sourceid/21101151614",
},

{
  slug: "library-progress-international",
  title: "Library Progress International",
  issn: "2320-317X / 0970-1052",
  category: "library-information-science",
  indexing: ["Scopus"],
  publisher: "BPAS Publications",
  ActiveYears: "Discontinued 2023",
  language: "English",
  image: "/images/JLPI.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101204534",
},

{
  slug: "journal-of-neonatal-surgery",
  title: "Journal of Neonatal Surgery",
  issn: "2226-0439",
  category: "medical",
  indexing: ["Scopus"],
  publisher: "EL-MED-Pub",
  ActiveYears: "Discontinued 2025",
  language: "English",
  image: "/images/JNS.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101039171",
},

{
  slug: "international-journal-of-environmental-sciences",
  title: "International Journal of Environmental Sciences",
  issn: "2229-7359",
  category: "environment-science-technology",
  indexing: ["Scopus"],
  publisher: "Academic Science Publications and Distributions",
  ActiveYears: "Discontinued 2024",
  language: "English",
  image: "/images/IJES.jpeg",
  Scopus: "https://www.scopus.com/sourceid/21101096350",
},
  {
  slug: "international-journal-of-economic-practices-and-theories",
  title: "International Journal of Economic Practices and Theories",
  issn: "2247-7225",
  category: "economics",
  indexing: ["ABDC"],
  ABDC: "C",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/IJEPT.png",
  Scopus: "",
  website: "https://www.ijapt.org",
},

{
  slug: "the-canadian-journal-of-marketing-research",
  title: "The Canadian Journal of Marketing Research (CJMR)",
  issn: "0829-4836",
  category: "marketing",
  indexing: ["ABDC"],
  ABDC: "C",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/CJMR.png",
  Scopus: "",
  website: "https://canadian-jmr.com/index.php/cjmr/index",
},

{
  slug: "advances-in-consumer-research",
  title: "Advances in Consumer Research",
  issn: "3079-1766",
  category: "marketing",
  indexing: ["Scopus", "ABDC"],
  ABDC: "B",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/ACR.png",
  Scopus: "https://www.scopus.com/sourceid/11600153426",
  website: "https://acr-journal.com/",
},

{
  slug: "minnesota-journal-of-business-law-and-entrepreneurship",
  title: "Minnesota Journal of Business Law and Entrepreneurship",
  issn: "1540-3270",
  category: "law-business",
  indexing: ["ABDC"],
  ABDC: "B",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/MJBLE.png",
  Scopus: "",
  website: "https://kommerstad.org/journal",
},

{
  slug: "academy-of-marketing-studies-journal",
  title: "Academy of Marketing Studies Journal",
  issn: "1095-6298",
  category: "marketing",
  indexing: ["ABDC"],
  ABDC: "B",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/AMSJ.png",
  Scopus: "",
  website:
    "https://www.abacademies.org/journals/academy-of-marketing-studies-journal-home.html",
},

{
  slug: "restitution-law-review",
  title: "Restitution Law Review",
  issn: "1351-170X",
  category: "law",
  indexing: ["ABDC"],
  ABDC: "A",
  publisher: "",
  ActiveYears: "",
  language: "English",
  image: "/images/RLR.png",
  Scopus: "",
  website: "https://restitutionlawreview.co.uk/",
},
];